"""expense tracker

Revision ID: 342fca98de7d
Revises: 83be959c9e94
Create Date: 2026-09-27 01:46:38.289248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# System categories every user sees: (name, lucide icon, chart color token).
SYSTEM_CATEGORIES = [
    ("Food & Dining", "utensils", "chart-1"),
    ("Groceries", "shopping-basket", "chart-2"),
    ("Transport", "car", "chart-3"),
    ("Rent", "house", "chart-4"),
    ("Utilities", "zap", "chart-5"),
    ("Shopping", "shopping-bag", "chart-1"),
    ("Entertainment", "clapperboard", "chart-2"),
    ("Travel", "plane", "chart-3"),
    ("Health", "heart-pulse", "chart-4"),
    ("Subscriptions", "repeat", "chart-5"),
    ("Education", "graduation-cap", "chart-1"),
    ("Other", "circle-ellipsis", "chart-2"),
]


# revision identifiers, used by Alembic.
revision: str = '342fca98de7d'
down_revision: Union[str, Sequence[str], None] = '83be959c9e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incomes',
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incomes_user_id_date', 'incomes', ['user_id', 'date'], unique=False)
    op.create_table('budgets',
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_budget_user_category', 'budgets', ['user_id', 'category_id'], unique=True, postgresql_where=sa.text('category_id IS NOT NULL'))
    op.create_index('uq_budget_user_overall', 'budgets', ['user_id'], unique=True, postgresql_where=sa.text('category_id IS NULL'))
    op.add_column('categories', sa.Column('icon', sa.String(length=32), nullable=True))
    op.add_column('categories', sa.Column('color', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###

    # Seed system categories. NULL user_id defeats uq_category_name_user, so
    # guard each insert by name to keep the migration safe to re-run.
    conn = op.get_bind()
    for name, icon, color in SYSTEM_CATEGORIES:
        conn.execute(
            sa.text(
                """
                INSERT INTO categories (id, name, is_system, user_id, icon, color)
                SELECT gen_random_uuid(), CAST(:name AS varchar), true, NULL, CAST(:icon AS varchar), CAST(:color AS varchar)
                WHERE NOT EXISTS (
                    SELECT 1 FROM categories WHERE user_id IS NULL AND lower(name) = lower(CAST(:name AS varchar))
                )
                """
            ),
            {"name": name, "icon": icon, "color": color},
        )
        conn.execute(
            sa.text(
                "UPDATE categories SET icon = :icon, color = :color, is_system = true "
                "WHERE user_id IS NULL AND lower(name) = lower(:name) AND icon IS NULL"
            ),
            {"name": name, "icon": icon, "color": color},
        )


def downgrade() -> None:
    """Downgrade schema."""
    conn = op.get_bind()
    conn.execute(
        sa.text("DELETE FROM categories WHERE user_id IS NULL AND is_system = true AND name = ANY(:names)"),
        {"names": [name for name, _, _ in SYSTEM_CATEGORIES]},
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'color')
    op.drop_column('categories', 'icon')
    op.drop_index('uq_budget_user_overall', table_name='budgets', postgresql_where=sa.text('category_id IS NULL'))
    op.drop_index('uq_budget_user_category', table_name='budgets', postgresql_where=sa.text('category_id IS NOT NULL'))
    op.drop_table('budgets')
    op.drop_index('ix_incomes_user_id_date', table_name='incomes')
    op.drop_table('incomes')
    # ### end Alembic commands ###
