"""check_changes

Revision ID: 83be959c9e94
Revises: c680f10680d5
Create Date: 2026-07-26 23:55:50.386847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83be959c9e94'
down_revision: Union[str, Sequence[str], None] = 'c680f10680d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_currency', 'quote_currency', 'as_of_date', name='uq_exchange_rate_day')
    )
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'user_id', name='uq_category_name_user')
    )
    op.create_table('chat_conversations',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_deleted_at'), 'groups', ['deleted_at'], unique=False)
    op.create_table('chat_messages',
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'TOOL', name='chat_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_invitations',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'CANCELLED', name='invitation_status'), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('invited_by_id', sa.UUID(), nullable=False),
    sa.Column('invited_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_invitations_email'), 'group_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_group_invitations_token'), 'group_invitations', ['token'], unique=True)
    op.create_index('uq_group_invitation_pending_email', 'group_invitations', ['group_id', 'email'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('group_members',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='group_role'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_member')
    )
    op.create_index(op.f('ix_group_members_group_id'), 'group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_members_user_id'), 'group_members', ['user_id'], unique=False)
    op.create_table('recurring_expenses',
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('split_type', sa.Enum('EQUAL', 'UNEQUAL', 'PERCENTAGE', name='split_type'), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='frequency'), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('next_run_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('paid_by_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paid_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_expenses_next_run_date'), 'recurring_expenses', ['next_run_date'], unique=False)
    op.create_table('settlements',
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('paid_by_id', sa.UUID(), nullable=False),
    sa.Column('received_by_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('paid_by_id != received_by_id', name='ck_settlement_distinct_parties'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paid_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_settlements_group_id', 'settlements', ['group_id'], unique=False)
    op.create_table('expenses',
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('split_type', sa.Enum('EQUAL', 'UNEQUAL', 'PERCENTAGE', name='split_type'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('paid_by_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('recurring_expense_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paid_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recurring_expense_id'], ['recurring_expenses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expenses_created_by_id', 'expenses', ['created_by_id'], unique=False)
    op.create_index('ix_expenses_date', 'expenses', ['date'], unique=False)
    op.create_index(op.f('ix_expenses_deleted_at'), 'expenses', ['deleted_at'], unique=False)
    op.create_index('ix_expenses_group_id', 'expenses', ['group_id'], unique=False)
    op.create_index('ix_expenses_group_id_date', 'expenses', ['group_id', 'date'], unique=False)
    op.create_index('ix_expenses_paid_by_id', 'expenses', ['paid_by_id'], unique=False)
    op.create_table('recurring_expense_splits',
    sa.Column('amount_owed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('share', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('recurring_expense_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recurring_expense_id'], ['recurring_expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recurring_expense_id', 'user_id', name='uq_recurring_split_user')
    )
    op.create_table('ai_expense_drafts',
    sa.Column('source_type', sa.Enum('RECEIPT_IMAGE', 'NL_TEXT', 'VOICE', name='ai_source_type'), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=1000), nullable=True),
    sa.Column('parsed_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'DISCARDED', 'EDITED', name='ai_draft_status'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resulting_expense_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resulting_expense_id'], ['expenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_splits',
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_owed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('share', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expense_id', 'user_id', name='uq_expense_split_user')
    )
    op.create_index('ix_expense_splits_user_id', 'expense_splits', ['user_id'], unique=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('default_currency', sa.String(length=3), server_default='INR', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_currency')
    op.drop_column('users', 'is_active')
    op.drop_index('ix_expense_splits_user_id', table_name='expense_splits')
    op.drop_table('expense_splits')
    op.drop_table('ai_expense_drafts')
    op.drop_table('recurring_expense_splits')
    op.drop_index('ix_expenses_paid_by_id', table_name='expenses')
    op.drop_index('ix_expenses_group_id_date', table_name='expenses')
    op.drop_index('ix_expenses_group_id', table_name='expenses')
    op.drop_index(op.f('ix_expenses_deleted_at'), table_name='expenses')
    op.drop_index('ix_expenses_date', table_name='expenses')
    op.drop_index('ix_expenses_created_by_id', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_settlements_group_id', table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_recurring_expenses_next_run_date'), table_name='recurring_expenses')
    op.drop_table('recurring_expenses')
    op.drop_index(op.f('ix_group_members_user_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_group_id'), table_name='group_members')
    op.drop_table('group_members')
    op.drop_index('uq_group_invitation_pending_email', table_name='group_invitations', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index(op.f('ix_group_invitations_token'), table_name='group_invitations')
    op.drop_index(op.f('ix_group_invitations_email'), table_name='group_invitations')
    op.drop_table('group_invitations')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_groups_deleted_at'), table_name='groups')
    op.drop_table('groups')
    op.drop_table('chat_conversations')
    op.drop_table('categories')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
